version: "1"
services:
  webapp:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27018
    volumes:
      - data:/data/db
volumes:
  data:
